# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-09-26 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2app', '0003_many_redirect_uris'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='refreshable',
            field=models.BooleanField(default=True),
        ),
    ]
